spring:
  application:
    name: group
  config:
    import: optional:configserver:http://localhost:8086

  zipkin:
    base-url: http://localhost:9411
  cloud:
    compatibility-verifier:
      enabled=false:

kafka:
  bootstrap-servers=broker:9092:
management:
  tracing:
    sampling:
      probability: 1.0
