spring:
  datasource:
    url: jdbc:postgresql://localhost:5225/partage_microservice
    username: partage_microservice
    password: partage_microservice
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8088
application:
  config:
    students-url: http://localhost:8089/auth
